AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  s3kindlehighlightstoses:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::975792760363:role/lambda-kindle-role'
      Environment:
        Variables:
            BUCKET: # your_s3_bucket
            EMAIL: # emails
            OBJECT: # name of higlights json manifest
            REGION: us-east-1
            SUBJECT: Daily Kindle Highlights # email subject
            CHARSET: utf-8
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            # Daily schedule for 3am PT
            Schedule: cron(0 10 * * ? *)

